---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault-admin
resources:
  - ./namespace.yaml
  - ./secret-engines/
  # - ./kube-auth-engine-config.yaml
  # - ./kube-auth-engine-mount.yaml
