apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuaySecretEngineConfig
metadata:
  name: quay
  namespace: vault-admin
spec:
  authentication: 
    path: dev-cluster-admin
    role: vault-admin
    serviceAccount:
      name: default
  disableSslVerification: true
  rootCredentials:
    vaultSecret:
      path: "kv/secrets/rhdh/registry-plugin"
      # path: "kv/data/secrets/{{ idp_instance_name }}/registry-plugin" # when using KV v2
      # This will map the "username" and "password" keys of the secret to the username and password of this config. All other keys will be ignored.
    # secret:
    #   name: quay-token
  path: quay
  url: "https://quay.io" #REPLACE-ME, if using a hosted Quay instance