apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuaySecretEngineRole
metadata:
  name: vault-quay-secret-engine-role
  namespace: vault-admin
spec:
  authentication: 
    path: dev-cluster-admin
    role: vault-admin
    serviceAccount:
      name: default
  path: quay
  namespaceName: "REPLACE-ME!!!"
  createRepositories: true
  defaultPermission: write
  TTL: "8760h" #1 year
  