kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'openshift-config-default-cluster-admin'
  labels:
    {{- include "openshift-config.labels" . | nindent 4 }}  
subjects:
  - kind: ServiceAccount
    name: default
    # .Release.Namespace will render the namespace where the application being installed by helm.
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'cluster-admin'