apiVersion: v1
kind: Secret
metadata:
  name: default-service-account
  namespace: openshift-config
  annotations:
    kubernetes.io/service-account.name: default
type: kubernetes.io/service-account-token