apiVersion: config.openshift.io/v1
kind: Build
metadata:
  annotations:
    release.openshift.io/create-only: "true"
  name: cluster
  labels:
    {{- include "openshift-config.labels" . | nindent 4 }}  
spec:
  buildDefaults:
    resources:
      requests:
        cpu: 200m
        memory: 500Mi