apiVersion: v1
kind: Secret
metadata:
  name: default-service-account-secret
  annotations:
    kubernetes.io/service-account.name: "default"
  labels:
    {{- include "openshift-config.labels" . | nindent 4 }}    
type: kubernetes.io/service-account-token