apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
  labels:
    {{- include "openshift-config.labels" . | nindent 4 }}  
data:
  config.yaml: |
    enableUserWorkload: true