apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/codekow/demo-ai-gitops-catalog/components/operators/openshift-cert-manager-operator/operator/overlays/stable-v1?ref=v0.03
