apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
spec:
  chart:
    version: 7.4.1
    values:
      certmanager-issuer:
        email: {{ .Values.certmanager.issuer.email }}
      configureCertmanager:
        install: false
      global:
        hosts:
          domain: example.com
        ingress:
          annotations:
            route.openshift.io/termination: edge
            kubernetes.io/tls-acme: true
          class: none
          # configureCertmanager: true
      nginx-ingress:
        enabled: false
