apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
spec:
  chart:
    version: 7.9.2
    values:
      certmanager-issuer:
        email: rafaelcba@gmail.com
      configureCertmanager:
        install: false
      global:
        hosts:
          domain: example.com # update with the cluster domain here.
        ingress:
          annotations:
            route.openshift.io/termination: edge
            kubernetes.io/tls-acme: true
          class: none
          # configureCertmanager: true
      nginx-ingress:
        enabled: false
