apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - ../../base

patches:
  - target:
      kind: Group
      name: gitops-admins
    patch: |-
      - op: replace
        path: /users
        value:
          - admin
          - opentlc-mgr
  - path: argocd.yaml
