apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/codekow/demo-ai-gitops-catalog/components/operators/kubernetes-imagepuller-operator/operator/overlays/stable?ref=v0.03
