apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-devspaces
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/redhat-cop/gitops-catalog
    targetRevision: main
    path: devspaces/instance/overlays/timeout-12m
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - SkipDryRunOnMissingResource=true
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true    
    retry:
      limit: 5
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
  ignoreDifferences:
  - group: org.eclipse.che
    kind: CheCluster
    name: devspaces
    jsonPointers:
    - /spec
