apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch-operator
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/redhat-na-ssa/redhat-developer-hub-gitops-bootstrap.git
    targetRevision: peer-review
    path: components/operators/patch-operator/operator/overlays/alpha
    # directory:
    #   include: operator.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: patch-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - SkipDryRunOnMissingResource=true
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true    
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
