apiVersion: redhatcop.redhat.io/v1alpha1
kind: GitHubSecretEngineConfig
metadata:
  name: github
  namespace: vault-admin
spec:
  authentication: 
    path: dev-cluster-admin
    role: vault-admin
  sSHKeyReference:
    vaultSecret:
      path: "kv/secrets/rhdh/github-plugin"
      # path: "kv/data/secrets/{{ idp_instance_name }}/github-plugin" # when using KV v2
      # the operator will search for a key named 'key' with value containing the Private Key (.pem)
    # secret:
    #   name: vault-github-plugin-creds
  path: github
  applicationID: 0001 #REPLACE-ME!!!