apiVersion: redhatcop.redhat.io/v1alpha1
kind: PasswordPolicy
metadata:
  name: git-webhook-password-policy
  namespace: vault-admin
spec:
  authentication: 
    path: dev-cluster-admin
    role: vault-admin 
  passwordPolicy: |
      length = 8
      rule "charset" {
        charset = "abcdefghijklmnopqrstuvwxyz"
        min-chars = 1
      }
      rule "charset" {
        charset = "0123456789"
        min-chars = 1
      }