apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: quay
spec:
  authentication: 
    path: dev-cluster-admin
    role: vault-admin
  type: vault-plugin-secrets-quay
  path: ""