apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gitwebhook-operator
  namespace: gitwebhook-operator
spec:
  # channel: alpha
  installPlanApproval: Automatic
  name: gitwebhook-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  # startingCSV: gitwebhook-operator.v0.1.0
