---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../operators/vault-config-operator/operator/overlays/alpha

patches:
  - patch: |-
      - op: replace
        path: /spec/config
        value: 
          config:
            env:
            - name: VAULT_ADDR
              value: https://vault.vault.svc:8200
            - name: VAULT_SKIP_VERIFY
              value: "true"
    target:
      kind: Subscription      
